services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: "bank_cards"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "secret"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db/init.sql:/docker-entrypoint-initdb.d/initDB.sql
    ports:
      - '6432:5432'
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d bank_cards" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: